name: Build

concurrency:
  group: build-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ master ]

  push:
    branches:
      - master
      - ci/pr-*-integration

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore ./ShippingRates/ShippingRates.csproj

      - name: Test (Unit)
        run: dotnet test --configuration Release --no-restore --verbosity minimal ./ShippingRates.Tests/ShippingRates.Tests.csproj

      - name: Test (Integration)
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
        env:
          ShippingRates.USPSClientId: ${{ secrets.USPS_CLIENT_ID }}
          ShippingRates.USPSClientSecret: ${{ secrets.USPS_CLIENT_SECRET }}
          ShippingRates.USPSUseProduction: ${{ secrets.USPS_USE_PRODUCTION }}
          ShippingRates.USPSUserId: ${{ secrets.USPS_USER_ID }}
          ShippingRates.UPSAccountNumber: ${{ secrets.UPS_ACCOUNT_NUMBER }}
          ShippingRates.UPSClientId: ${{ secrets.UPS_CLIENT_ID }}
          ShippingRates.UPSClientSecret: ${{ secrets.UPS_CLIENT_SECRET }}
          ShippingRates.FedExClientId: ${{ secrets.FEDEX_CLIENT_ID }}
          ShippingRates.FedExClientSecret: ${{ secrets.FEDEX_CLIENT_SECRET }}
          ShippingRates.FedExUseProduction: ${{ secrets.FEDEX_USE_PRODUCTION }}
          ShippingRates.FedExHubId: ${{ secrets.FEDEX_HUB_ID }}
          ShippingRates.FedExAccountNumber: ${{ secrets.FEDEX_ACCOUNT_NUMBER }}
          ShippingRates.DHLSiteId: ${{ secrets.DHL_SITE_ID }}
          ShippingRates.DHLPassword: ${{ secrets.DHL_PASSWORD }}
          ShippingRates.DHLAccountNumber: ${{ secrets.DHL_ACCOUNT_NUMBER }}
        run: dotnet test --configuration Release --no-restore --verbosity minimal ./ShippingRates.IntegrationTests/ShippingRates.IntegrationTests.csproj
